version: '3.1'
services:
  docker-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /docker/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
